#!/bin/bash

docker run -it -v $HOME/.vim/:/home/developer/.vim/ \
               -v `pwd`/.vimrc:/home/developer/.vimrc \
               -v $HOME/Workspace/:/workspace \
               duykhoa/vim:0.1 sh
